# Generated by Django 4.2.1 on 2023-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
                ('email', models.EmailField(default=False, max_length=100)),
                ('reviews', models.TextField(default=False, max_length=400)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
