# Generated by Django 4.2.1 on 2023-07-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
