# Generated by Django 4.2.1 on 2023-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_review_product_name_alter_review_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviews',
            field=models.TextField(default=False, max_length=400),
        ),
    ]
