# Generated by Django 4.2.1 on 2023-07-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_review_product_name_alter_review_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
